name: "Dependency Submission"

on:
  push:
  pull_request:

permissions:
  contents: "write"

jobs:
  dependencies:
    runs-on: "ubuntu-latest"
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2

      # https://github.com/marketplace/actions/setup-java
      - name: "Set up JDK 21"
        uses: "actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00" # v4.7.1
        with:
          java-version: "21"
          distribution: "temurin"

      # https://github.com/marketplace/actions/build-with-gradle
      - name: "Generate and submit dependency graph"
        uses: "gradle/actions/dependency-submission@8379f6a1328ee0e06e2bb424dadb7b159856a326" # v4.4.0
